version: "3.8"
services:
  som:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      FORCE_CUDA: 0
    # env_file:
    #   - .env
    # image: ghcr.io/feedback-box/SOM:latest
    restart: always
    ports:
      - 8080:6092
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:6092"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  ghcr:
    environment:
      FORCE_CUDA: 0
    image: ghcr.io/feedback-box/som:main
    restart: always
    ports:
      - 8080:6092
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:6092"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
